spring:
  application:
    name: ${APPLICATION_NAME}
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    hikari:
      poolName: Retail Hikari
      auto-commit: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update