spring:
  application:
    name: ${APPLICATION_NAME}
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    hikari:
      poolName: minio
      auto-commit: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${SERVER_PORT}

logging:
  level:
    ROOT: info
    uz.retail: info

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
  show-actuator: false
  api-docs:
    enabled: true
    path: "/v2/api-docs"
    version: openapi_3_0
